# Generated by Django 4.2.7 on 2023-11-15 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('status', models.CharField(default='unknown', max_length=255)),
                ('species', models.CharField(default='unknown', max_length=255)),
                ('type', models.CharField(default='unknown', max_length=255)),
                ('gender', models.CharField(default='unknown', max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.ImageField(blank=True, upload_to='uploads/images/character/')),
                ('episode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('type', models.CharField(default='unknown', max_length=255)),
                ('dimension', models.CharField(default='unknown', max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('character_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapper.character')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('air_date', models.CharField(max_length=255)),
                ('episode', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('characters', models.ManyToManyField(related_name='episodes', to='scrapper.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrapper.location'),
        ),
    ]
