# Generated by Django 4.2.7 on 2023-11-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dimension',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
    ]
