# Generated by Django 4.2.7 on 2023-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_location_dimension_alter_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='unknown', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='unknown', max_length=255, unique=True),
        ),
    ]
