# Generated by Django 4.2.7 on 2023-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_alter_character_name_alter_episode_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/character/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
    ]
