# Generated by Django 4.2.7 on 2023-11-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_remove_character_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrapper.location'),
        ),
    ]
